config/routes.rb
BasicUser::Application.routes.draw do
  resources :users
  resources :logins
  root :to => 'users#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  
  extend FriendlyId
  friendly_id :username
  
  has_secure_password
  
  attr_accessible :password, :password_confirmation, :username, :email
  
  validates :username, :uniqueness => true, :format => { :with => /^[a-zA-Z0-9_]+$/ }
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :email, :uniqueness => true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  helper_method :current_user

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController

  def new
  end
  
  def create
    user = User.find_by_username(params[:username])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      session[:username] = user.username
      redirect_to :root
    else
      redirect_to("/logins/new?invalid_password=true&email=#{params[:username]}")
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to(:root)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    if current_user.username == params[:id]
      @user = User.find(params[:id])
    else
      redirect_to(:root)
    end
  end

  def create
    @user = User.new(params[:user])
    
    if @user.save
      session[:user_id] = @user.id # "auto-login"
      
      redirect_to(:root)
    else
      render "new"
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    
    redirect_to(:root)
  end

  def destroy
    @user = User.find(params[:id])
    if current_user.id = @user.id
      session[:user_id] = nil
    end
    @user.delete
    
    redirect_to(:users)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def session_status(current_user)
    if current_user
      render :partial => "shared/session_status", locals: { current_user: current_user }
    else
      render :partial => "shared/login_prompt"
    end
  end
  
  def footer_text
    render :partial => "shared/footer_text"
  end
  
  def nav_bar
    render :partial => "shared/nav_bar"
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.haml
<!DOCTYPE html>
%html
  %head
    %title Basic User
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body.cf
    #wrapper
      #header.cf
        = nav_bar

app/views/logins/new.html.erb
<% if params[:invalid_password] == "true" %>
  <p>Invalid password for username <%= params[:username] %></p>
<% end %>
<h1>Log In</h1>

<h3>Not a user? <%= link_to("Sign up now!", :new_user) %></h3>
<%= form_tag logins_path do %>

  <%= label_tag :username %>
  <%= text_field_tag :username %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>
  
  <%= submit_tag "Log In" %>
<% end %>

app/views/shared/_footer_text.html.haml
%p My Studio Simplified™ by Matt Hova

app/views/shared/_login_prompt.html.haml
= link_to("Sign In", new_login_path, :class => "login_status")

app/views/shared/_nav_bar.html.erb
<a class="square" href="#">
  <div class="plus_sign" id="horizontal"></div>
  <div class="plus_sign" id="vertical"></div>
</a>

app/views/shared/_session_status.html.haml
= link_to("Hello, #{current_user.username}", user_path(current_user.id), :class => "login_status")

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error_msg| %>
      <p><%= error_msg %></p>
    <% end %>
  <% end %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  
  <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User Info</h1>

<%= render :partial => "form" %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <p>
    <%= link_to(user.username, user_path(user.id)) %> 
  </p>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render :partial => "form" %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>